projects:
  challengeMeGraphQL:
    schemaPath: amplify/backend/api/challengeMeGraphQL/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: rjadncgkkbbqrox6ryn372pav4
        maxDepth: 2
extensions:
  amplify:
    version: 3
