export const FETCH_CHALLENGES = 'FETCH_CHALLENGES';
export const FETCH_CHALLENGES_SUCCESS = 'FETCH_CHALLENGES_SUCCESS';
export const FETCH_CHALLENGES_FAIL = 'FETCH_CHALLENGES_FAIL';

export const FETCH_CHALLENGE = 'FETCH_CHALLENGE';
export const FETCH_CHALLENGE_SUCCESS = 'FETCH_CHALLENGE_SUCCESS';
export const FETCH_CHALLENGE_FAIL = 'FETCH_CHALLENGE_FAIL';

export const ACCEPT_CHALLENGE = 'ACCEPT_CHALLENGE';
export const ACCEPT_CHALLENGE_SUCCESS = 'ACCEPT_CHALLENGE_SUCCESS';
export const ACCEPT_CHALLENGE_FAIL = 'ACCEPT_CHALLENGE_FAIL';

export const REJECT_CHALLENGE = 'REJECT_CHALLENGE';
export const REJECT_CHALLENGE_SUCCESS = 'REJECT_CHALLENGE_SUCCESS';
export const REJECT_CHALLENGE_FAIL = 'REJECT_CHALLENGE_FAIL';

export const SET_CHALLENGE_WINNER = 'SET_CHALLENGE_WINNER';
export const SET_CHALLENGE_WINNER_SUCCESS = 'SET_CHALLENGE_WINNER_SUCCESS';
export const SET_CHALLENGE_WINNER_FAIL = 'SET_CHALLENGE_WINNER_FAIL';

export const CREATE_CHALLENGE_INIT = 'CREATE_CHALLENGE_INIT';
export const CREATE_CHALLENGE = 'CREATE_CHALLENGE';
export const CREATE_CHALLENGE_SUCCESS = 'CREATE_CHALLENGE_SUCCESS';
export const CREATE_CHALLENGE_FAIL = 'CREATE_CHALLENGE_FAIL';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_NOT_FOUND = 'FETCH_PROFILE_NOT_FOUND';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';