// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_content_delivery_bucket": "challenge-me-react-20190330154210-hostingbucket-production",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://challenge-me-react-20190330154210-hostingbucket-production.s3-website.eu-central-1.amazonaws.com"
};


export default awsmobile;
