// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_content_delivery_bucket": "challenge-me-react-20190330154210-hostingbucket-production",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://challenge-me-react-20190330154210-hostingbucket-production.s3-website.eu-central-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://kgxopwzhjjgcbpyfbsp6ctjfaa.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-central-1:56caf5bc-7275-4bb0-95d4-df8c16890190",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_QCNGhmsfX",
    "aws_user_pools_web_client_id": "1rg2f7k3htji7ifunhjdqd156d"
};


export default awsmobile;
