const sports = [
  { name: "Other", emoji: "🏆" },
  { name: "Football", emoji: "⚽️" },
  { name: "Badminton", emoji: "🏸" },
  { name: "Volleyball", emoji: "🏐" },
  { name: "Tennis", emoji: "🎾" },
  { name: "Ping Pong", emoji: "🏓" },
  { name: "Basketball", emoji: "🏀" },
  { name: "Baseball", emoji: "⚾" },
  { name: "Cricket", emoji: "🏏" },
  { name: "Skateboarding", emoji: "🛹" },
  { name: "Skiing", emoji: "⛷" },
  { name: "Snowboarding", emoji: "🏂" },
  { name: "Surfing", emoji: "🏄‍" },
  { name: "Climbing", emoji: "🧗" },
  { name: "Cycling", emoji: "🚴‍" },
  { name: "Fishing", emoji: "🎣" },
  { name: "Golf", emoji: "⛳️" },
  { name: "Handball", emoji: "🤾‍" },
  { name: "Hunting", emoji: "🏹" },
  { name: "Curling", emoji: "🥌" },
  { name: "Hockey", emoji: "🏑" },
  { name: "Rugby", emoji: "🏉" },
  { name: "Dancing", emoji: "💃" },
  { name: "Riding", emoji: "🏇" },
  { name: "Swimming", emoji: "🏊‍♀️" },
  { name: "Biking", emoji: "🚴‍♂️" },
  { name: "Bowling", emoji: "🎳" },
  { name: "Boxing", emoji: "🥊" },
  { name: "Ice Skating", emoji: "⛸️" },
  { name: "Darts", emoji: "🎯" }
];
export default sports;
