export const FETCH_CHALLENGES_START = 'FETCH_CHALLENGES_START';
export const FETCH_CHALLENGES_SUCCESS = 'FETCH_CHALLENGES_SUCCESS';
export const FETCH_CHALLENGES_FAIL = 'FETCH_CHALLENGES_FAIL';

export const CREATE_CHALLENGE_INIT = 'CREATE_CHALLENGE_INIT';
export const CREATE_CHALLENGE_START = 'CREATE_CHALLENGE_START';
export const CREATE_CHALLENGE_SUCCESS = 'CREATE_CHALLENGE_SUCCESS';
export const CREATE_CHALLENGE_FAIL = 'CREATE_CHALLENGE_FAIL';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';